### ISSUE TITLE
Specific value "-2" doesn't work ???

### ISSUE THREAD

**Issue by qabi** [axedan80/nibegw#1]
I don't know if this is an issue in my actual heat pump controller (VVM500) or perhaps somehow in nibegw?

Writing values to 47032 (external adjustment) works for values 3, 2, 1, 0, -1, -3 and -4 but NOT for -2. That seems very strange.

Actual data sent:

-1: `c06b06b8b7ff0000005d` (works)
-2: `c06b06b8b7fe0000005c` (no response)
-3: `c06b06b8b7fd0000005f`(works)

Any ideas or insights?

**Comment by axedan80** [comment]
Hi, unfortunately not. The code is from: [https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/RasPi]. Please have a look there.

This code doesn't work for me. I cannot get connection to the serial port and I haven't had time to look for a solution. Maybe I have issues with my hardware.

**Comment by qabi** [comment]
After further research it turns out that it was an issue (in the client code) with the checksum. Apparently there is a "magical" exception where cheksum = 5c must be turned into c5 (hex).
